name: Push-to-EC2

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - main

jobs:
  build-front-01:
    name: Deploy Front Web 1
    runs-on: ubuntu-latest
    steps:
      - name: Publicando nova versão
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            nvm install 14
            nvm use 14
            cd /home/ubuntu/FREELA-Web
            git pull
            yarn cache clean
            yarn build
            sudo cp -r /home/ubuntu/FREELA-Web/dist/* /var/www/html/
            sudo systemctl restart nginx

  build-front-02:
    name: Deploy Front Web 2
    runs-on: ubuntu-latest
    steps:
      - name: Publicando nova versão
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS_02 }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            nvm install 14
            nvm use 14
            cd /home/ubuntu/FREELA-Web
            git pull
            yarn cache clean
            yarn build
            sudo cp -r /home/ubuntu/FREELA-Web/dist/* /var/www/html/
            sudo systemctl restart nginx
            