name: Push-to-EC2

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - main

jobs:
  build-front-01:
    name: Build Front-01
    runs-on: ubuntu-latest
    steps:
      - name: Conectando na EC2 front-01 e atualizando repositorio
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/FREELA-Web
            git pull
            yarn cache clean
            yarn install
            yarn build
            sudo cp -r /home/ubuntu/FREELA-Web/dist/* /var/www/html/
            sudo systemctl restart nginx
  build-front-02:
    name: Build Front-02
    runs-on: ubuntu-latest
    steps:
      - name: Conectando na EC2 front-02 e atualizando repositorio
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS_02 }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/FREELA-Web
            git pull
            yarn cache clean
            yarn install
            yarn build
            sudo cp -r /home/ubuntu/FREELA-Web/dist/* /var/www/html/
            sudo systemctl restart nginx