name: Deploy da aplicacao no nginx

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Build and Deploy
        run: |
          ssh -i ${{ secrets.EC2_SSH_KEY }} ubuntu@ec2-52-207-200-178.compute-1.amazonaws.com

          cd /home/ubuntu/FREELA-Web
          yarn
          sudo systemctl restart freela
