name: Push-to-EC2

on:
  push:
    branches:
      - main

jobs:
  build-front-01:
    name: Build Front-01
    runs-on: ubuntu-latest
    steps:
      - name: Conectar na EC2 front-01 e atualizar repositório
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            nvm install 14
            nvm use 14
            cd /home/ubuntu/FREELA-Web
            git pull

      - name: Instalar Dependências e Construir
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            yarn cache clean
            yarn build

      - name: Copiar para /var/www/html/
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo cp -r /home/ubuntu/FREELA-Web/dist/* /var/www/html/

      - name: Reiniciar Nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo systemctl restart nginx

  build-front-02:
    name: Build Front-02
    runs-on: ubuntu-latest
    steps:
      - name: Conectar na EC2 front-02 e atualizar repositório
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS_02 }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            nvm install 14
            nvm use 14
            cd /home/ubuntu/FREELA-Web
            git pull

      - name: Instalar Dependências e Construir
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS_02 }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            yarn cache clean
            yarn build

      - name: Copiar para /var/www/html/
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS_02 }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo cp -r /home/ubuntu/FREELA-Web/dist/* /var/www/html/

      - name: Reiniciar Nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS_02 }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo systemctl restart nginx
