name: Deploy da aplicacao no nginx

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: appleboy/ssh-action@master
        with:
          host: ec2-52-207-200-178.compute-1.amazonaws.com
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Build and Deploy
        run: |
          cd /home/ubuntu/FREELA-Web
          yarn
          sudo systemctl restart freela
